name: Run Tests

on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install Dependencies
        run: |
          pip install types-requests pytest pytest-cov requests-mock mypy

      - name: Run Mypy
        run: mypy api_manager.py

      - name: Run Tests with Coverage
        run: pytest --cov=api_manager test_api.py
